### ISSUE TITLE
Explore concurrency options

### ISSUE THREAD

**Issue by nicmr** [Altemista/billing#29]
Currently, each outgoing API request  (e.g. to AWS, Azure) blocks the entire program when using the cli interface and the entire handler when using http interface. We should run these requests in their own goroutines.

**Comment by cheld** [comment]
Use go restful. For job execution no problem

**Comment by nicmr** [comment]
Support for concurrent uploads has been added with #48. Concurrent api calls will be implemented once we actually support several cost APIs, and will receive its own issue at that point. Closing.
