### ISSUE TITLE
Rework flag and configuration file approach

### ISSUE THREAD

**Issue by cheld** [Altemista/billing#47]
Code looks correct, but somehow the flags are not processed properly:

1. help not working
2. the check for the bucket flags should be handled by cobra https://github.com/Altemista/altemista-billing/blob/master/cmd/invoice.go#L61
**3. Viper only makes sense for global (persistent) flags, I think**

**Comment by nicmr** [comment]
1. I have no issues using `altemista-billing help` or `altemista-billing help invoice`. Could you please provide steps to reproduce the issue?

2. It is alreadyhandled by cobra, in https://github.com/Altemista/altemista-billing/blob/master/cmd/invoice.go#L47 . Viper tries to retrieve the flag with the following priority: Cobra cli flag > ConfigFile > Default value

3. Kubernetes .yaml specs allow many job-specific flags, which is fairly similar to what we're trying to achieve with the config file. But I'm definitely interested in discussing this further.

**Comment by nicmr** [comment]
Trying to modify a flag value of a subcommand when a global config file has been read results in some very messy code. I believe we should scrap the config file support altogether, until a real use case for it arises. It is not used in its current deployment.

**Comment by nicmr** [comment]
Viper config support will be removed with #53 .

An interesting alternative could be a job descriptor file, but viper is definitely not the right tool for our use case.

**Comment by nicmr** [comment]
If a use case for a config file arises, we can open a separate issue. With the removal of viper with #53 this issue can be considered complete.
